In [1]:
a=10
b=4
if(a<b):
    print("dhananjay")
else:
    print("i am not valid")

i am not valid


In [2]:
list (range(10,20,4))

[10, 14, 18]

In [3]:
import numpy as np
l=[54,67,54,43,3,45,76,5]
arr=np.array(l)


In [4]:
l

[54, 67, 54, 43, 3, 45, 76, 5]

In [5]:
arr

array([54, 67, 54, 43,  3, 45, 76,  5])

In [6]:
np.arange(10,34)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.random.randint(0,23)

8

In [11]:
np.random.randint(0,10,(5,5))

array([[9, 2, 4, 3, 2],
       [9, 1, 8, 3, 4],
       [0, 1, 3, 9, 0],
       [7, 4, 3, 8, 8],
       [5, 8, 1, 7, 7]], dtype=int32)

In [12]:
a=np.random.randint(10,20,30)

In [13]:
a

array([17, 10, 19, 10, 19, 16, 10, 15, 17, 18, 18, 18, 19, 14, 18, 17, 19,
       12, 19, 15, 11, 13, 13, 14, 14, 11, 11, 15, 12, 19], dtype=int32)

In [14]:
np.random.randint(1,100,20)

array([70, 97, 95, 64, 24,  6, 32, 89, 61, 26, 59, 37, 38, 65,  2, 94,  7,
       17, 10, 56], dtype=int32)

In [15]:
b=np.random.randint(0,100,20)

In [16]:
b

array([61, 96, 29, 15, 14, 75,  1, 41, 67, 14, 98, 88, 54, 16,  3, 76, 28,
       78, 39, 45], dtype=int32)

In [ ]:
b.max()

In [ ]:
b.mean()

In [9]:
b.min()

AttributeError: 'int' object has no attribute 'min'

In [ ]:
b.reshape(2,2)

In [ ]:
b

In [ ]:
b.reshape(6,4)

In [ ]:
mat=np.arange(0,100).reshape(10,10)

In [ ]:
row=4
col=3
mat[row,col]

In [ ]:
mat

In [ ]:
mat

In [ ]:
mat

In [ ]:
mat=np.arange(0,100).reshape(10,10)

In [ ]:
mat

In [ ]:
row=4
col=3
mat[row,col]

In [ ]:
mat[:,col]

In [ ]:
mat[row,:]

In [ ]:
mat>50

In [ ]:
mat[mat>50]

In [ ]:
mydata=np.arange(0,20)
print(mydata)

In [ ]:
import numpy as np
mydata=np.arange(0,20)
print(mydata)

In [ ]:
mtr1=np.reshape(mydata,(4,5),order='C')

In [ ]:
mtr1

In [ ]:
mtr1=np.reshape(mydata,(4,5),order='f')

In [ ]:
mtr1

In [ ]:
mtr1[-3,-1]#here '-' value use this time index will be reversre

In [ ]:
mtr1[0:3]

In [ ]:
  mtr1[2:3]

In [ ]:
mtr2=np.reshape(mydata,(4,5),order='A')

In [ ]:
mtr2

In [ ]:
mtr2[0,4]

In [ ]:
mtr2[2,3] #index start from 0 here

In [ ]:
mtr2[0:4]

In [ ]:
mtr2[3:4]

In [ ]:
mtr2[3:2]

In [ ]:
mtr2[2,2]